### ISSUE TITLE
Null Pointer Exception onDisable

### ISSUE THREAD

**Issue by hitech95** [Double0negative/Survival-Games#46]
Hi,
This is the error:
2013-06-09 15:34:02 [SEVERE] Error occurred while disabling SurvivalGames v0.5.8.42 (Is it up to date?)
java.lang.NullPointerException
    at org.mcsg.survivalgames.logging.QueueManager.rollback(QueueManager.java:67)
    at org.mcsg.survivalgames.SurvivalGames.onDisable(SurvivalGames.java:53)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:219)
    at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:481)
    at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:400)
    at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:393)
    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.disablePlugins(CraftServer.java:277)
    at net.minecraft.server.v1_5_R3.MinecraftServer.stop(MinecraftServer.java:334)
    at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:441)
    at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)

It is generated on plugin disable. I'm running the latest dev bukkit version under Windows 8 whit latest JDK (64bit).
The installed plugins are:
Permission Ex, Vault, SurvivalGames, Multiverse-Core, World Edit. (All updated at latest version)

I have also removed all plugin (SurvivalGames and World Edit excluded) but the error persists.

**Comment by JamieSinn** [comment]
Its an issue with the rollback system, you would need to remove the map and readd it
